title: "newspaper"
description: "Sample of newspaper Jekyll theme."
author:
  name: "newspaper"
  email: "mail@example.com"
  
url: "https://vllur.github.io"
baseurl: /newspaper

source: .
destination: ./_site
permalink: /:title
paginate: 2
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
exclude: [vendor]
plugins:
  - jekyll-paginate

# Custom variables
google_analytics: ""
owner : "vellur"
